make import in=can_config.vhdl && \
make import in=can_subprograms.vhdl && \
make import in=can_crc.vhdl && \
make import in=can_deserializer.vhdl && \
make import in=can_equalizer.vhdl && \
make import in=can_master.vhdl && \
make import in=can_phy.vhdl && \
make import in=can_receiver.vhdl && \
make import in=can_serializer.vhdl && \
make import in=can_wire.vhdl && \
make in=can_master_coord.vhdl